version: "3"

services:
  todolist.api:
    container_name: todolist.api
    image: node
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/api
      - ./api/node_modules:/app/outside/node_modules
    working_dir: /usr/src/api
    env_file:
      - ./api/.env.dev
    command: bash -c 'npm i && npm run dev'
    links:
      - todolist.db
  todolist.db:
    container_name: todolist.db
    image: mariadb
    env_file:
      - ./mariadb/.env
    volumes:
      - ./mariadb_data:/var/lib/mysql
  todolist.adminer:
    container_name: todolist.adminer
    image: adminer
    ports:
      - 9090:8080
    links:
      - todolist.db
